/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aforoTemperatura;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import com.panamahitek.PanamaHitek_MultiMessage;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
/**
 *
 * @author alex_
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    PanamaHitek_Arduino ino = new PanamaHitek_Arduino();
    
    PanamaHitek_MultiMessage multi = new PanamaHitek_MultiMessage(2, ino);

    SerialPortEventListener listener = new SerialPortEventListener() {
        @Override   
        public void serialEvent(SerialPortEvent serialPortEvent) {
            try {
                
                if (multi.dataReceptionCompleted()) {
                    /**
                     * Se imprimen los datos recibidos del Arduino en el mismo
                     * orden en el que son enviados. Los indices 0, 1, 2 y 3
                     * indican el cual dato se debe imprimir
                     */

                    txt_aforo.setText(multi.getMessage(0));
                    txt_temperatura.setText(multi.getMessage(1));


                    /*
                    Cuando se ha terminado de imprimir los datos, se invoca el 
                    flushBuffer para que se pueda recibir el siguiente set de datos
                     */
                    multi.flushBuffer();
                }
            } catch (SerialPortException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ArduinoException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    };
    public Ventana() {
        setIconImage(getIconImage());
        initComponents();
        
        setTitle("Aforo - Temperatura ");
        
        setResizable(false);
        setLocationRelativeTo(null);
        

        try {
            //Se inicializa la conexion con el Arduino en el puerto COM5
            ino.arduinoRXTX("COM20", 9600, listener);
        } catch (ArduinoException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        };
        
        URL url = Ventana.class.getResource("/images/DS.png");
        ImageIcon wallapper_logo = new ImageIcon(url);
        Icon icono_logo = new ImageIcon(wallapper_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(),
                jLabel_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icono_logo);
        this.repaint();
        
        url = Ventana.class.getResource("/images/wallpaperPrincipal.jpg");
        ImageIcon wallpaper = new ImageIcon(url);
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    };
    
    @Override
    public Image getIconImage() {
        URL url = Ventana.class.getResource("/images/DS.png");
        Image retValue = Toolkit.getDefaultToolkit().getImage(url);
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_aforo = new javax.swing.JLabel();
        txt_temperatura = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aforo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, 130));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AFORO ACTUAL:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TEMPERATURA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txt_aforo.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        txt_aforo.setForeground(new java.awt.Color(255, 255, 255));
        txt_aforo.setText("jLabel3");
        getContentPane().add(txt_aforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        txt_temperatura.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        txt_temperatura.setForeground(new java.awt.Color(255, 255, 255));
        txt_temperatura.setText("jLabel4");
        getContentPane().add(txt_temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("XTREME GYM");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel3.setText("Xtreme Gym ®");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        aforo.setBackground(new java.awt.Color(51, 51, 51));
        aforo.setText("- -");
        aforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aforoActionPerformed(evt);
            }
        });
        getContentPane().add(aforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 80, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicializar contador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aforoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aforoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                //Se envia el contenido por el puerto serie al Arduino
                ino.sendData(aforo.getText());
            } catch (ArduinoException | SerialPortException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aforo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel txt_aforo;
    private javax.swing.JLabel txt_temperatura;
    // End of variables declaration//GEN-END:variables
}
